# Generated by Django 3.1.6 on 2021-04-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='Date Article Published')),
                ('category', models.CharField(max_length=20)),
                ('ingredients', models.CharField(max_length=1000)),
                ('instructions', models.CharField(max_length=10000)),
            ],
        ),
    ]
